### ISSUE TITLE
no rostopic

### ISSUE THREAD

**Issue by Nimingez** [devvaibhav455/UR5_VR_teleop#2]
rostopic vive_gripper Publishers:None
that leads to typeerror

**Comment by Nimingez** [comment]
I just
<img width="1280" alt="Snipaste_2023-11-23_16-26-16" src="https://github.com/devvaibhav455/UR5_VR_teleop/assets/104558844/5eeb7b19-eba5-4ef1-a490-576a34204dcd">
Start ROS core: roscore
Disable simulation time: rosparam set use_sim_time false
Open SteamVR
Source your workspace: source ~/Documents/ur5_teleop_ws/devel/setup.bash
Launch the HTC Vive teleop package: roslaunch htc_vive_teleop_stuff vive_tf_joy_and_ps.launch
Launch the UR5 robot package: roslaunch ur5_teleop_vive ur5_bringup.launch
source ~/Documents/ur5_teleop_ws/devel/setup.bash
cd ~/Documents/ur5_teleop_ws/src/ur5_teleop_vive/src/
Remember to change your robot's IP in the script before running it
python3 ur_follow_using_class.py

**Comment by Nimingez** [comment]
my rviz and after run python3 ur_follow_using.py 
![Uploading 微信图片_20231124095018.jpg…]()
![Uploading 2.jpg…]()

**Comment by devvaibhav455** [comment]
@Nimingez : Do you see anything on the `/vive_right` and `right_controller_as_posestamped` topics?

**Comment by Nimingez** [comment]
yes I find that topic vive_gripper is published in vive_ur5_teleop.py  so I just follow these steps
Start ROS core: roscore
Disable simulation time: rosparam set use_sim_time false
Open SteamVR
Source your workspace: source ~/Documents/ur5_teleop_ws/devel/setup.bash
Launch the HTC Vive teleop package: roslaunch htc_vive_teleop_stuff vive_tf_joy_and_ps.launch
Launch the UR5 robot package: roslaunch ur5_teleop_vive ur5_bringup.launch
source ~/Documents/ur5_teleop_ws/devel/setup.bash
cd ~/Documents/ur5_teleop_ws/src/ur5_teleop_vive/src/
python3 vive_ur5_teleop.py
Remember to change your robot's IP in the script before running it
python3 ur_follow_using_class.py
but rivz is robomodel error

**Comment by devvaibhav455** [comment]
Yes, but is there any data on those topics apart from just being present there?

**Comment by Nimingez** [comment]
I do not have roboiq so i need change some code
when i click the trigger i vive_right will change

**Comment by Nimingez** [comment]
I want to know why you close the robot here?
ur_dollow_using_class.py
def main():
    
    rospy.init_node('my_node')
    my_object = ur_follow_vive()
    print(" ################# READY TO CONTROL #################")
    time.sleep(5)
    my_object.robot.close()

**Comment by Nimingez** [comment]
Can you give me an email? It would be convenient for me to record a video tomorrow to introduce my situation to you. Thank you very much.

**Comment by devvaibhav455** [comment]
I suggest you post a video here/on YouTube so that it may benefit anyone else who shares the same issue as yours.

Answering your question: I want to know why you close the robot here?
While developing and testing the script, I guess sometimes when I used to run the script, a successful connection was not made to the robot sometimes because of the previous run's CTRL+C/ Z. And I think this helped in improving the repetitive success rate of running the script. However, if it causes trouble to you, you may remove it.

**Comment by Nimingez** [comment]
Traceback (most recent call last):
  File "/home/nmz/ur5_teleop_ws/src/ur5_teleop_vive/src/ur_follow_using_class.py", line 357, in <module>
    main()
  File "/home/nmz/ur5_teleop_ws/src/ur5_teleop_vive/src/ur_follow_using_class.py", line 344, in main
    my_object.control_action()
  File "/home/nmz/ur5_teleop_ws/src/ur5_teleop_vive/src/ur_follow_using_class.py", line 174, in control_action
    goal = oriented_xyz.get_pose_vector()
AttributeError: 'Transform' object has no attribute 'get_pose_vector'

my python is 3.8

**Comment by Nimingez** [comment]
when I trigger the trigger 
![ab804a19d3c776593607a3f1e426ac1](https://github.com/devvaibhav455/UR5_VR_teleop/assets/104558844/31f97bb2-6990-4362-81e0-db2964ad2701)

**Comment by Nimingez** [comment]
ur_follow_using_class
 orientation_q = self.vive_gripper_data.pose.orientation
        orientation_list = [orientation_q.x, orientation_q.y, orientation_q.z, orientation_q.w]
        (roll, pitch, yaw) = euler_from_quaternion (orientation_list)

        # print("Pose from gripper",pose_goal.position.x, pose_goal.position.y, pose_goal.position.z )          
        
        xyz_coords = m3d.Vector(pose_goal.position.x, pose_goal.position.y, pose_goal.position.z)
        # print("xyz_coords: ",xyz_coords )

        # tcp_rotation_rpy = [roll, pitch, yaw] #Vive Gripper/ Controller Pose

        # tcp_rotation_rpy = [0, math.radians(180), 0] # Testing Only
        # tcp_rotation_rpy = [0.08252318, current_pose[4], 0.03336271] # Top-Down pose
        tcp_rotation_rpy = [0.08252318, math.radians(180) , 0.03336271] # Top-Down pose

        # tcp_rotation_rvec = convert_rpy(tcp_rotation_rpy)
        tcp_orient = m3d.Orientation.new_euler(tcp_rotation_rpy, encoding='xyz')
        # print("tcp_orient: ",tcp_orient )
        

        oriented_xyz = m3d.Transform(tcp_orient, xyz_coords)
        # print("oriented_xyz: ",oriented_xyz )
        
        goal = oriented_xyz.get_pose_vector()
 Is this project only capable of controlling the end effector to face downwards? What should I do if I want to have different orientations?

**Comment by devvaibhav455** [comment]
From the steam screenshot, it looks like the HTC Vive controller might not be outputting values. Did you double check if it is throwing numbers through the verification steps mentioned in the Readme?

This project as of now works with top-down orientation but just with a slight change can work with all the orientations.

Replace line# 191 in `ur_follow_using_class.py` should work:
`goal[-3:] = [roll, pitch, yaw]`

**Comment by Nimingez** [comment]
thank you！I have sovled those problem! but now
Traceback (most recent call last):
File "/home/nmz/ur5_teleop_ws/src/ur5_teleop_vive/src/ur_follow_using_class.py", line 357, in
main()
File "/home/nmz/ur5_teleop_ws/src/ur5_teleop_vive/src/ur_follow_using_class.py", line 344, in main
my_object.control_action()
File "/home/nmz/ur5_teleop_ws/src/ur5_teleop_vive/src/ur_follow_using_class.py", line 174, in control_action
goal = oriented_xyz.get_pose_vector()
AttributeError: 'Transform' object has no attribute 'get_pose_vector'

m3d.Transform
my python is 3.8

**Comment by devvaibhav455** [comment]
Have you installed all the dependencies mentioned in [https://github.com/devvaibhav455/UR5_VR_teleop/blob/master/ur5_teleop_vive/src/requirements.txt](https://github.com/devvaibhav455/UR5_VR_teleop/blob/master/ur5_teleop_vive/src/requirements.txt)?

**Comment by Nimingez** [comment]
my tcp position is x:0.118 y:-0.480 z:0.291 rx:2.2091 ry:2.19 rz:-0.046 joint 90 -90 90 -90 -90 90
How should I  calibrate it?
i can not understand the teleop.yaml offset_real trans_x trans_y trans_x rot_x rot_y rot_z means 
![2179de59e65b1b882e803c202b3e674](https://github.com/devvaibhav455/UR5_VR_teleop/assets/104558844/0c50961f-120a-433b-99d7-33654aad42d0)

**Comment by Nimingez** [comment]
Thank you for your great work. I have successfully reproduced it.

**Comment by devvaibhav455** [comment]
Awesome.. Congratulations! The tcp value that the pendant/ script outputs should be as per the configuration specified in the teach pendant. In my case, the z value reported had an offset of 0.175 which is observed in line # 189, 324, and 332. I suggest you to check the configuration in your teach pendant (the tablet that UR provides with the robot) to see for what point in the 3D space, it reports the values.

Regarding the VR calibration, the values reported by the HTC controller are with respect to the base station(s) (don't ask me how/ frames.. I simply don't know !). I tried to place and orient them in such a way that the actual joystick movement should reflect the desired movement in rviz/ the real robot. For e.g. First define an area in which you would want to sit and move the joystick. If for a certain direction, you want the robot to go left, make sure that values in other directions don't change.
The offsets in the yaml file are there because sometimes, the marker in rviz is way-off from the simulated robot. So, some offsets need to be applied to make it closer to the robot/ your workspace and these are the offsets for my setup in the yaml file. For this, please refer to the `Calibration` section of the readme. It can be done with either hit and trial or educated guess (try to see different frames in rviz and it will all make sense).

All the best!
